### PR TITLE
Question on use-package

### PR DESCRIPTION
**Pull request by randomwangran**

### CODE REVIEW

**Comment by randomwangran** [comment]
I call it digital minimalism, and it applies the belief that less can be more to our relationship with digital tools.

Newport, Cal. Digital Minimalism (p. xv). Penguin Publishing Group. Kindle Edition.

**Comment by ghost** [comment]
@randomwangran Check the README:

> I don't advise people to use it directly and I won't be accepting pull requests (after all that's my config, right?).

**Comment by randomwangran** [comment]
> @randomwangran Check the README:
> 
> > I don't advise people to use it directly and I won't be accepting pull requests (after all that's my config, right?).

;; This is my personal Emacs configuration.  Nothing more, nothing less.

I've tested the `:ensure t` and it works.

I try to make it more

> Nothing more, nothing less.

Of course, it's owner's will to make decision. I just present a possibility.

**Comment by ghost** [comment]
> > @randomwangran Check the README:
> > > I don't advise people to use it directly and I won't be accepting pull requests (after all that's my config, right?).
> 
> ;; This is my personal Emacs configuration. Nothing more, nothing less.
> 
> I've tested the `:ensure t` and it works.
> 
> I try to make it more
> 
> > Nothing more, nothing less.
> 
> Of course, it's owner's will to make decision. I just present a possibility.

That's not what "Nothing more, nothing less" means in this context. It means that `init.el` is only a personal configuration.

**Comment by randomwangran** [comment]
> > > @randomwangran Check the README:
> > > > I don't advise people to use it directly and I won't be accepting pull requests (after all that's my config, right?).
> > 
> > 
> > ;; This is my personal Emacs configuration. Nothing more, nothing less.
> > I've tested the `:ensure t` and it works.
> > I try to make it more
> > > Nothing more, nothing less.
> > 
> > 
> > Of course, it's owner's will to make decision. I just present a possibility.
> 
> That's not what "Nothing more, nothing less" means in this context. It means that `init.el` is only a personal configuration.

"Impossible" -Dick Feynman

**Comment by a13** [comment]
@randomwangran 

> I've tested the :ensure t and it works.

I can't see why it shouldn't work as designed. 

The thing is it makes packages installation implicit (which itself is not a good thing, usually), but the worst thing here it makes people think that use-package is a package manager (which is not).


And LBNL: it will break the config completely, since internal packages shouldn't be ensured

**Comment by randomwangran** [comment]
@a13

[A group of people are discussing this .emacs.](https://emacs-china.org/t/use-package/8600/4), especially, the meaning of :ensure.

>I can't see why it shouldn't work as designed.

Sorry, are you agree with me, i.e., deleting all the :ensure?

I re-read the manual again:

> The ‘:ensure’ keyword causes the package(s)
> to be installed automatically if not already present on your system (set
> ‘(setq use-package-always-ensure t)’ if you wish this behavior to be
> global for all packages):
>
>      (use-package magit
>        :ensure t)

I've check the creator's dot emacs file: git@github.com:bbatsov/emacs.d.git

There's 61 package.

There are 42 packages using :ensure, so I think majority of this
ini.el want to make sure the pacakge is automatically installed if not
find on some computer.

So, the user could claim 19 `:ensure nil', which might save some space here.

This leads my further question: why some packages are not ensure?


Here is a non-inclusive list of the user that don't want to ensure:

paren elec-pair  hl-line  abbrev abbrev uniquify saveplace savehist recentf windmove dired lisp-mode ielm zenburn-theme avy

Does this imply those packages are not important?



>The thing is it makes packages installation implicit (which itself is
not a good thing, usually), but the worst thing here it makes people
think that use-package is a package manager (which is not).

I agree with you, although I am not fully using an explicit method,
such as a submodule. I will try to make it in the near future.

> package manager (which is not)?

Maybe, people have different view of package manager. I think it is a
package manager because it managers so many elisp packages. But, does it important?

>And LBNL: it will break the config completely, since internal packages
shouldn't be ensured

~~What is LBNL?~~ (last but not least?)

I think you are talking about example like:  `(use-package isearch)'?


I am still studying it, but yet to draw a solid conclusion. Sorry for such a long delay.

**Pull request closed without merging**
